version: '3.7'
x-othentic-cli: &othentic-cli
  env_file:
    - .env
  build:
    context: .
    dockerfile: ./Dockerfile
services:
  aggregator:
    <<: *othentic-cli
    command: [
      "node",
      "aggregator",
      "--json-rpc",
      # Enable custom messaging if needed 
      # "--json-rpc.custom-message-enabled",
      "--l1-chain", "mainnet",
      # Set the L2 chain 
      "--l2-chain", "base", 
      "--internal-tasks",
      "--metrics",
      "--p2p.datadir", "data/peerstore/aggregator"
    ]
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY_AGGREGATOR}
      - LOG_DIR=data/logs/aggregator
    volumes:
      - ./data/peerstore/aggregator:/app/data/peerstore/aggregator
      - ./data/logs/aggregator:/app/data/logs/aggregator
    ports:
      - "8545:8545"
      - "9876:9876"
    networks:
      p2p:
        ipv4_address: 10.8.0.69
  attester-1:
    <<: *othentic-cli
    command: [
      "node",
      "attester",
      "/ip4/10.8.0.69/tcp/9876/p2p/${OTHENTIC_BOOTSTRAP_ID}",
      # Enable custom messaging if needed 
      # "--json-rpc",
      # "--json-rpc.custom-message-enabled",
      "--avs-webapi",
      "http://10.8.0.42",
      "--l1-chain", "mainnet",
      # Set the L2 chain 
      "--l2-chain", "base",
      "--metrics",
      "--p2p.datadir", "data/peerstore/attester1",
      # Setup using https://docs.othentic.xyz/main/avs-framework/othentic-cli/node-operators#features
      "--announced-addresses",
      "/ip4/${ATTESTER1_IP}/tcp/9876/p2p/${PEER_ID}" # Replace Attester IP and its peer id
    ]
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY_ATTESTER1}
      - LOG_DIR=data/logs/attester1
    volumes:
      - ./data/peerstore/attester1:/app/data/peerstore/attester1
      - ./data/logs/attester1:/app/logs/peerstore/attester1
    depends_on:
      aggregator:
        condition: service_started
    networks:
      p2p:
        ipv4_address: 10.8.0.2
  attester-2:
    <<: *othentic-cli
    command: [
      "node",
      "attester",
      "/ip4/10.8.0.69/tcp/9876/p2p/${OTHENTIC_BOOTSTRAP_ID}",
      # Enable custom messaging if needed 
      # "--json-rpc",
      # "--json-rpc.custom-message-enabled",
      "--avs-webapi",
      "http://10.8.0.42",
      "--l1-chain", "mainnet",
      # Set the L2 chain 
      "--l2-chain", "base",
      "--metrics",
      "--p2p.datadir", "data/peerstore/attester2",
      # Setup using https://docs.othentic.xyz/main/avs-framework/othentic-cli/node-operators#features
      "--announced-addresses",
      "/ip4/${ATTESTER2_IP}/tcp/9876/p2p/${PEER_ID}" # Replace Attester IP and its peer id
    ]
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY_ATTESTER2}
      - LOG_DIR=data/logs/attester2
    volumes:
      - ./data/peerstore/attester2:/app/data/peerstore/attester2
      - ./data/logs/attester2:/app/logs/peerstore/attester2
    depends_on:
      aggregator:
        condition: service_started
    networks:
      p2p:
        ipv4_address: 10.8.0.3
  attester-3:
    <<: *othentic-cli
    command: [
      "node",
      "attester",
      "/ip4/10.8.0.69/tcp/9876/p2p/${OTHENTIC_BOOTSTRAP_ID}",
      # Enable custom messaging if needed 
      # "--json-rpc",
      # "--json-rpc.custom-message-enabled",
      "--avs-webapi",
      "http://10.8.0.42",
      "--l1-chain", "mainnet",
      # Set the L2 chain 
      "--l2-chain", "base",
      "--metrics",
      "--p2p.datadir", "data/peerstore/attester3",
      # Setup using https://docs.othentic.xyz/main/avs-framework/othentic-cli/node-operators#features
      "--announced-addresses",
      "/ip4/${ATTESTER3_IP}/tcp/9876/p2p/${PEER_ID}" # Replace Attester IP and its peer id
    ]
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY_ATTESTER3}
      - LOG_DIR=data/logs/attester3
    volumes:
      - ./data/peerstore/attester3:/app/data/peerstore/attester3
      - ./data/logs/attester3:/app/logs/peerstore/attester3
    depends_on:
      aggregator:
        condition: service_started
    networks:
      p2p:
        ipv4_address: 10.8.0.4
  validation-service:
    build:
      context: ./Validation_Service
      dockerfile: ./Dockerfile
    env_file:
      - .env
    networks:
      p2p:
        ipv4_address: 10.8.0.42
  execution-service:
    build:
      context: ./Execution_Service
      dockerfile: ./Dockerfile
    environment:
      - OTHENTIC_CLIENT_RPC_ADDRESS=http://10.8.0.69:8545
      - PRIVATE_KEY=${PRIVATE_KEY_PERFORMER}
    env_file:
      - .env
    ports:
      - "4003:4003"
    networks:
      p2p:
        ipv4_address: 10.8.0.101
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml  # Bind mount the config file
    ports:
      - "9090:9090"  # Expose Prometheus on port 9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'  # Specify the config file location
    restart: unless-stopped
    networks:
      p2p:
        ipv4_address: 10.8.0.102
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      p2p:
        ipv4_address: 10.8.0.103
    environment:
    - GF_SECURITY_ADMIN_USER=admin
    - GF_SECURITY_ADMIN_PASSWORD=admin #Here you can set the password for the admin user
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage: {}

networks:
  p2p:
    driver: bridge
    ipam:
     config:
       - subnet: 10.8.0.0/16
         gateway: 10.8.0.1
